### PR TITLE
manage admin user for mongodb + use ValidateDiagFunc

### LINKED ISSUE #588: [BUG] Terraform/OVH API crashes randomly
### Describe the bug
Hi, not sure if this indeed is a provider bug, feels a lot more like an API bug, but here it goes: Terraform plan/apply randomly crashes  with timeouts/500 response code/other errors. There is a business support ticket exists for this very issue on OVH already (9391258), but in 2 weeks we got absolutely nowhere. Opening the bug here as per the suggestion on Discord.

### Terraform Version

```bash
terraform -v
Terraform v1.7.5
on darwin_arm64
```

### OVH Terraform Provider Version

0.39.0 and 0.40.0
Earlier versions had the same or similar issues.

### Affected Resource(s)

- ovh_cloud_project_kube
- ovh_cloud_project_kube_nodepool
- ovh_cloud_project_database_ip_restriction
- ovh_cloud_project_database_mongodb_user
- ovh_cloud_project_database

Would also list here the VM instances resource as well, but that is a different provider. Essentially any resource we use can cause issues.

This is not an issue with Terraform core as other providers elsewhere works just fine, or restarting the plan/apply - sometimes multiple times - gets the job done eventually.

### Terraform Configuration Files

```hcl
provider "ovh" {
  endpoint           = var.ovh_endpoint
  application_key    = var.ovh_application_key
  application_secret = var.ovh_application_secret
  consumer_key       = var.ovh_consumer_key
  alias              = "ovh"
}
provider "openstack" {
  user_name   = var.openstack_user
  password    = var.openstack_password
  auth_url    = "https://auth.cloud.ovh.net/v3/" # Authentication URL
  domain_name = "default"
  alias       = "ovh"
  tenant_id   = var.ovh_service_name
}

terraform {
  required_providers {
    openstack = {
      source                = "terraform-provider-openstack/openstack"
      version               = "1.54.1"
      configuration_aliases = [openstack.ovh]
    }
    ovh = {
      source                = "ovh/ovh"
      version               = "0.39.0"
      configuration_aliases = [ovh.ovh]
    }
  }

  backend "http" {
    address        = "[REDACTED]"
    lock_address   = "[REDACTED]"
    unlock_address = "[REDACTED]"
    lock_method    = "POST"
    unlock_method  = "DELETE"
    retry_wait_min = 5
  }
}

## Snippets only, the entire config is over 400 different resources

variable "authorized_networks_beta_ovh" {
  description = "List of authorized networks to be used for managed databases"
  type        = map(any)
  default = {
    "243ce7" = {
      description = "243ce7"
      ip          = "0.1.2.3/32"
    }
    "3db359" = {
      description = "3db359"
      ip          = "4.5.6.7/32"
    }
    "4690d8" = {
      description = "4690d8"
      ip          = "8.9.10.11/32"
    }
}

resource "ovh_cloud_project_database" "mysql_beta" {
  provider    = ovh.ovh
  description = "beta-mysql"
  disk_size   = 80
  advanced_configuration = {
    "mysql.sql_mode"                = "ANSI,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_ALL_TABLES"
    "mysql.sql_require_primary_key" = "true"
  }
  engine                  = "mysql"
  flavor                  = "db1-4"
  opensearch_acls_enabled = false
  plan                    = "business"
  service_name            = "3985b358e7d049e6b6dd4044a40fdcfe"
  version                 = "8"

  nodes {
    region = "DE"
  }
  nodes {
    region = "DE"
  }

}

resource "ovh_cloud_project_database" "psql_beta" {
  provider = ovh.ovh
  advanced_configuration = {
    "pglookout.max_failover_replication_time_lag" = "60"
  }
  description             = "beta-psql"
  disk_size               = 80
  engine                  = "postgresql"
  flavor                  = "db1-4"
  opensearch_acls_enabled = false
  plan                    = "business"
  service_name            = var.ovh_service_name
  version                 = "15"

  nodes {
    region = "DE"
  }
  nodes {
    region = "DE"
  }
}

resource "ovh_cloud_project_database" "mongodb_beta" {
  provider                = ovh.ovh
  description             = "beta-mongo"
  disk_size               = 40
  engine                  = "mongodb"
  flavor                  = "db2-4"
  opensearch_acls_enabled = false
  plan                    = "production"
  service_name            = var.ovh_service_name
  version                 = "6.0"

  nodes {
    region = "DE"
  }
  nodes {
    region = "DE"
  }
  nodes {
    region = "DE"
  }
}

resource "ovh_cloud_project_database_ip_restriction" "restricted-ips-mongo-beta" {
  provider     = ovh.ovh
  for_each     = var.authorized_networks_beta_ovh
  service_name = var.ovh_service_name
  cluster_id   = ovh_cloud_project_database.mongodb_beta.id
  engine       = ovh_cloud_project_database.mongodb_beta.engine
  description  = each.value.description
  ip           = each.value.ip
}

resource "ovh_cloud_project_database_ip_restriction" "restricted-ips-mysql-beta" {
  provider     = ovh.ovh
  for_each     = var.authorized_networks_beta_ovh
  service_name = var.ovh_service_name
  cluster_id   = ovh_cloud_project_database.mysql_beta.id
  engine       = ovh_cloud_project_database.mysql_beta.engine
  description  = each.value.description
  ip           = each.value.ip
}

resource "ovh_cloud_project_database_ip_restriction" "restricted-ips-psql-beta" {
  provider     = ovh.ovh
  for_each     = var.authorized_networks_beta_ovh
  service_name = var.ovh_service_name
  cluster_id   = ovh_cloud_project_database.psql_beta.id
  engine       = ovh_cloud_project_database.psql_beta.engine
  description  = each.value.description
  ip           = each.value.ip
}

resource "ovh_cloud_project_kube" "development_cluster" {
  service_name    = var.ovh_service_name
  name            = var.k8s_name
  region          = var.k8s_region
  version         = var.k8s_version
  kube_proxy_mode = "iptables"
  update_policy   = "ALWAYS_UPDATE"
}

resource "ovh_cloud_project_kube_nodepool" "development_cluster_pool" {
  service_name   = var.ovh_service_name
  kube_id        = ovh_cloud_project_kube.development_cluster.id
  name           = "${var.k8s_name}-pool"
  flavor_name    = var.k8s_machine_type
  desired_nodes  = var.k8s_node_count
  max_nodes      = var.k8s_max_nodes
  min_nodes      = var.k8s_min_nodes
  monthly_billed = false
  autoscale      = true
}

resource "ovh_cloud_project_kube_nodepool" "development_cluster_me_pool" {
  service_name   = var.ovh_service_name
  kube_id        = ovh_cloud_project_kube.development_cluster.id
  name           = "${var.k8s_name}-me-pool"
  flavor_name    = var.k8s_machine_type
  desired_nodes  = var.me_k8s_node_count
  max_nodes      = var.me_k8s_max_nodes
  min_nodes      = var.me_k8s_min_nodes
  monthly_billed = false
  autoscale      = true
  template {
    metadata {
      annotations = {}
      finalizers  = []
      labels = {
        medical-engine = "true"
        component      = "medical-engine"
      }
    }
    spec {
      unschedulable = false
      taints = [
        {
          effect = "NoSchedule"
          key    = "special"
          value  = "true"
        }
      ]
    }
  }
}

resource "ovh_cloud_project_kube_oidc" "development-oidc" {
  service_name        = var.ovh_service_name
  kube_id             = ovh_cloud_project_kube.development_cluster.id
  client_id           = "[REDACTED]"
  issuer_url          = "https://accounts.google.com"
  oidc_username_claim = "email"
}
```

### Debug Output

The most common outputs we see: https://gist.github.com/apinter/cdda84c7eb975c2f52beff5d701bd488

### Expected Behavior

Terraform can be used seamlessly with OVH to deploy resources.

### Actual Behavior

Terraform/OVH API randomly crashes rendering an unreliable 

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`

The more resources the more likely it will crash, but can happen with a simple 4 resource deployment as well or with an MKS cluster upgrade. (This just happened yesterday when we upgraded from 1.26 to 1.27 with TF, timed out after 10 minutes)

### Additional context

This is not a networking error on our end. Doesn't matter where are we running the deployment from it can end up with a crash. 
Support suggested that we reach a ratelimit, but based on the official documentation that should give a 429 response, not a 500. Even if we reach a ratelimit, and the endpoint responds with 500, that is a bug.

### PR DESCRIPTION
**Pull request by lpatte**
# Description

Manage mongodb admin user like avnadmin user for other engines

Related #588 (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (improve existing resource(s) or datasource(s))
- [ ] Documentation update

### CODE REVIEW

File: ovh/helpers/helpers.go [hunk 1]
```diff
@@ -64,6 +66,19 @@ func ValidateEnum(enum []string) schema.SchemaValidateFunc {
 	}
 }
 
+func ValidateDiagEnum(enum []string) schema.SchemaValidateDiagFunc {
+	return func(v any, p cty.Path) (diags diag.Diagnostics) {
+		err := ValidateStringEnum(v.(string), enum)
+		if err != nil {
+			diags = append(diags, diag.Diagnostic{
```
Comment (amstuta) [inline ovh/helpers/helpers.go:73]: note: you could just use `diags.AddError()`

File: ovh/types_cloud_project_database.go [hunk 2]
```diff
@@ -1281,6 +1279,18 @@ func (opts *CloudProjectDatabaseMongodbUserUpdateOpts) FromResource(d *schema.Re
 	return opts
 }
 
+func validateCloudProjectDatabaseMongodbUserAuthenticationDatabase(v any, p cty.Path) (diags diag.Diagnostics) {
+	value := v.(string)
+	if !strings.Contains(value, "@") {
+		diags = append(diags, diag.Diagnostic{
+			Severity: diag.Error,
+			Summary:  "Missing authentication database",
+			Detail:   fmt.Sprintf("value %s do not have authentication database", value),
```
Comment (amstuta) [inline ovh/types_cloud_project_database.go:1288]:
```suggestion
			Detail:   fmt.Sprintf("value %s does not have authentication database", value),
```

File: ovh/data_cloud_project_database_mongodb_user.go [hunk 3]
```diff
@@ -54,36 +55,39 @@ func dataSourceCloudProjectDatabaseMongodbUser() *schema.Resource {
...
 	listRes := make([]string, 0)
 
-	log.Printf("[DEBUG] Will read users from cluster %s from project %s", clusterId, serviceName)
+	log.Printf("[DEBUG] Will read users from cluster %s from project %s", clusterID, serviceName)
 	if err := config.OVHClient.GetWithContext(ctx, listEndpoint, &listRes); err != nil {
 		return diag.Errorf("Error calling GET %s:\n\t %q", listEndpoint, err)
 	}
 
 	name := d.Get("name").(string)
+	if name == "admin" {
```
Comment (amstuta) [inline ovh/data_cloud_project_database_mongodb_user.go:73]: can you really get there considering this line: https://github.com/ovh/terraform-provider-ovh/pull/609/files#diff-914dfbdacc3d33ba986c5cc7c2ec9931d84789eb769aec8102c606e0a82d07c5R31 ?

File: website/docs/r/cloud_project_database_mongodb_user.html.markdown [hunk 4]
```diff
@@ -60,11 +60,8 @@ The following arguments are supported:
 
 * `service_name` - (Required, Forces new resource) The id of the public cloud project. If omitted,
   the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
-
 * `cluster_id` - (Required, Forces new resource) Cluster ID.
-
-* `name` - (Required, Forces new resource) Name of the user.
-
+* `name` - (Required, Forces new resource) Name of the user. A user named "admin" is map with already created admin@admin user instead of create a new user.
```
Comment (amstuta) [inline website/docs/r/cloud_project_database_mongodb_user.html.markdown:64]:
```suggestion
* `name` - (Required, Forces new resource) Name of the user. A user named "admin" is mapped with already created admin@admin user instead of creating a new user.
```

File: ovh/helpers/helpers.go (hunk 1 above)
Comment (lpatte) [reply ovh/helpers/helpers.go:73]: "terraform-plugin-framework/diag" has it not "terraform-plugin-sdk/v2/diag"

File: ovh/data_cloud_project_database_mongodb_user.go (hunk 3 above)
Comment (lpatte) [reply ovh/data_cloud_project_database_mongodb_user.go:73]: Yes because the special case for user admin in `ovh/resource_cloud_project_database_mongodb_user.go` will call `ovh/data_cloud_project_database_mongodb_user.go:dataSourceCloudProjectDatabaseMongodbUserRead()` with name = "admin"

File: website/docs/r/cloud_project_database_m3db_user.html.markdown [hunk 5]
```diff
@@ -61,13 +61,9 @@ The following arguments are supported:
...
 * `service_name` - (Required, Forces new resource) The id of the public cloud project. If omitted,
   the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
-
 * `cluster_id` - (Required, Forces new resource) Cluster ID.
-
 * `group` - (Optional) Group of the user:
-
-* `name` - (Required, Forces new resource) Name of the user. A user named "avnadmin" is map with already created admin user instead of create a new user.
-
+* `name` - (Required, Forces new resource) Name of the user. A user named "avnadmin" is map with already created admin user instead of creating a new user.
```
Comment (amstuta) [inline website/docs/r/cloud_project_database_m3db_user.html.markdown:66]:
```suggestion
* `name` - (Required, Forces new resource) Name of the user. A user named "avnadmin" is mapped with already created admin user instead of creating a new user.
```

File: website/docs/r/cloud_project_database_opensearch_user.html.markdown [hunk 6]
```diff
@@ -86,9 +84,7 @@ The following arguments are supported:
     * `write`
     * `readwrite`
     * `deny`
-
-* `name` - (Required, Forces new resource) Username affected by this acl. A user named "avnadmin" is map with already created admin user and reset his password instead of create a new user.
-
+* `name` - (Required, Forces new resource) Username affected by this acl. A user named "avnadmin" is map with already created admin user and reset his password instead of creating a new user.
```
Comment (amstuta) [inline website/docs/r/cloud_project_database_opensearch_user.html.markdown:87]:
```suggestion
* `name` - (Required, Forces new resource) Username affected by this acl. A user named "avnadmin" is mapped with already created admin user and reset his password instead of creating a new user.
```

File: website/docs/r/cloud_project_database_postgresql_user.html.markdown [hunk 7]
```diff
@@ -60,15 +60,11 @@ The following arguments are supported:
 
 * `service_name` - (Required, Forces new resource) The id of the public cloud project. If omitted,
   the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
-
 * `cluster_id` - (Required, Forces new resource) Cluster ID.
-
-* `name` - (Required, Forces new resource) Name of the user. A user named "avnadmin" is map with already created admin user and reset his password instead of create a new user.
-
+* `name` - (Required, Forces new resource) Name of the user. A user named "avnadmin" is map with already created admin user and reset his password instead of creating a new user.
```
Comment (amstuta) [inline website/docs/r/cloud_project_database_postgresql_user.html.markdown:64]:
```suggestion
* `name` - (Required, Forces new resource) Name of the user. A user named "avnadmin" is mapped with already created admin user and reset his password instead of creating a new user.
```

File: website/docs/r/cloud_project_database_user.html.markdown [hunk 8]
```diff
@@ -68,20 +68,15 @@ The following arguments are supported:
...
   * `kafkaConnect`
   * `mysql`
   * `grafana`
-
-
 * `cluster_id` - (Required, Forces new resource) Cluster ID.
-
-* `name` - (Required, Forces new resource) Name of the user. A user named "avnadmin" is map with already created admin user and reset his password instead of create a new user. The "Grafana" engine only allows the "avnadmin" mapping.
-
+* `name` - (Required, Forces new resource) Name of the user. A user named "avnadmin" is map with already created admin user and reset his password instead of creating a new user. The "Grafana" engine only allows the "avnadmin" mapping.
```
Comment (amstuta) [inline website/docs/r/cloud_project_database_user.html.markdown:79]:
```suggestion
* `name` - (Required, Forces new resource) Name of the user. A user named "avnadmin" is mapped with already created admin user and reset his password instead of creating a new user. The "Grafana" engine only allows the "avnadmin" mapping.
```

**Review by amstuta — APPROVED** [review]
