### PR TITLE
fix: Fetch plan configurations when reading orders

### LINKED ISSUE #704: [BUG] ovh_cloud_project has constantly the same change after apply with 0.48.0
### Describe the bug

Having a resource in my state (created via <= `0.45.0`) looking like this

```
resource "ovh_cloud_project" "cloud_project" {
    access         = "full"
    description    = "Production"
    id             = "C"
    ovh_subsidiary = "DE"
    project_id     = "A"
    project_name   = "B"
    status         = "ok"
    urn            = "urn:v1:eu:resource:publicCloudProject:XXX"

    order {
        date            = "2024-07-03T12:24:23+02:00"
        details         = [
            {
                description     = "Public Cloud Project rental for 1 month"
                domain          = "XXX"
                order_detail_id = 1022538057
                quantity        = "1"
            },
            {
                description     = "Public Cloud Project rental for 1 month"
                domain          = "XXX"
                order_detail_id = 1022538056
                quantity        = "1"
            },
            {
                description     = "/cloud project activation"
                domain          = "XXX"
                order_detail_id = 1022538058
                quantity        = "1"
            },
        ]
        expiration_date = "2024-07-17T23:29:59+02:00"
        order_id        = 212426011
    }

    plan {
        catalog_name = null
        duration     = "P1M"
        plan_code    = "project.2018"
        pricing_mode = "default"

        configuration {
            label = "vrack"
            value = "pn-X"
        }
    }
}     
```

leads to constant plan of

```
      ~ plan {
            # (4 unchanged attributes hidden)

          + configuration {
              + label = "vrack"
              + value = "pn-X"
            }
        }
```

### Terraform Version

Terraform v1.9.3

### OVH Terraform Provider Version

+ provider registry.terraform.io/ovh/ovh v0.48.0

### Affected Resource(s)

Please list the resources as a list, for example:
- ovh_cloud_project

### Terraform Configuration Files

```hcl
data "ovh_me" "account" {}

data "ovh_order_cart" "cart" {
  ovh_subsidiary = data.ovh_me.account.ovh_subsidiary
}

data "ovh_order_cart_product_plan" "cloud" {
  cart_id        = data.ovh_order_cart.cart.id
  price_capacity = "renew"
  product        = "cloud"
  plan_code      = "project.2018"
}

resource "ovh_cloud_project" "cloud_project" {
  ovh_subsidiary = data.ovh_order_cart.cart.ovh_subsidiary
  description    = var.name

  plan {
    duration     = data.ovh_order_cart_product_plan.cloud.selected_price[0].duration
    plan_code    = data.ovh_order_cart_product_plan.cloud.plan_code
    pricing_mode = data.ovh_order_cart_product_plan.cloud.selected_price[0].pricing_mode
    configuration {
      label = "vrack"
      value = var.vrack
    }
  }
}
```

### Expected Behavior

After first `apply`, no more changes.

### Actual Behavior

Same change all the time.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply`

### PR DESCRIPTION
**Pull request by amstuta**
# Description

Retrieve the `configurations` given at order time in resource `ovh_cloud_project`.

Fixes #704 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (improve existing resource(s) or datasource(s))
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

- [ ] Test A: `make testacc TESTARGS="-run TestAccResourceCloudProject_basic"`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or issues
- [x] I have added acceptance tests that prove my fix is effective or that my feature works
- [x] New and existing acceptance tests pass locally with my changes
- [x] I ran succesfully `go mod vendor` if I added or modify `go.mod` file

### CODE REVIEW

File: ovh/order.go [hunk 1]
```diff
@@ -528,6 +528,14 @@ func orderDetails(c *ovh.Client, orderId int64) ([]*MeOrderDetail, error) {
 			return nil, fmt.Errorf("calling get %s:\n\t %q", endpoint, err)
 		}
 
+		detailExtension := &MeOrderDetailExtension{}
+		log.Printf("[DEBUG] Will read order detail extension %d/%d", orderId, detailId)
```
Comment (mxpetit) [inline ovh/order.go:532]:
```suggestion
```

**Review by mxpetit — CHANGES_REQUESTED** [review]

**Review by mxpetit — APPROVED** [review]
