### PR TITLE
fix: Retry calls to Logs Data Platform streams and aliases

### LINKED ISSUE #1285: [BUG][Logs Data Platform] Resource busy when attaching a stream to an OpenSearch alias
### Describe the bug

When I try to create two streams, then two OpenSearch aliases attached to those streams, the apply fails with a Client::Forbidden::Busy error on one of the aliases.

### Terraform Version

v1.14.7

### OVH Terraform Provider Version

v2.12.0

### Affected Resource(s)

- ovh_dbaas_logs_output_opensearch_alias

### Terraform Configuration Files

```hcl
data "ovh_dbaas_logs_cluster" "logs_cluster" {
  service_name = "ldp-xx-xxxxx"
}

resource "ovh_dbaas_logs_output_graylog_stream" "stream" {
  count        = 2
  service_name = data.ovh_dbaas_logs_cluster.logs_cluster.service_name
  title        = "stream-${count.index}"
  description  = "stream-${count.index}"
}

resource "ovh_dbaas_logs_output_opensearch_alias" "alias" {
  count        = length(ovh_dbaas_logs_output_graylog_stream.stream)
  service_name = data.ovh_dbaas_logs_cluster.logs_cluster.service_name
  description  = "alias for stream-${count.index}"
  suffix       = "stream-${count.index}"
  streams = [
    ovh_dbaas_logs_output_graylog_stream.stream[count.index].id
  ]
}
```

### Debug Output

```
ovh_dbaas_logs_output_opensearch_alias.alias[1]: Creating...
ovh_dbaas_logs_output_opensearch_alias.alias[0]: Creating...
ovh_dbaas_logs_output_opensearch_alias.alias[0]: Still creating... [00m10s elapsed]
ovh_dbaas_logs_output_opensearch_alias.alias[1]: Still creating... [00m10s elapsed]
ovh_dbaas_logs_output_opensearch_alias.alias[1]: Still creating... [00m20s elapsed]
ovh_dbaas_logs_output_opensearch_alias.alias[1]: Still creating... [00m30s elapsed]
ovh_dbaas_logs_output_opensearch_alias.alias[1]: Still creating... [00m40s elapsed]
ovh_dbaas_logs_output_opensearch_alias.alias[1]: Still creating... [00m50s elapsed]
ovh_dbaas_logs_output_opensearch_alias.alias[1]: Still creating... [01m00s elapsed]
ovh_dbaas_logs_output_opensearch_alias.alias[1]: Creation complete after 1m1s [id=ded7848e-1ce5-4940-9af4-0b520b6e74c6]
╷
│ Error: Error calling post /dbaas/logs/ldp-fs-82198/output/opensearch/alias/1b34bf85-ed8d-422a-9a76-aaed9f4bfd3f/stream:
│        "OVHcloud API error (status code 403): Client::Forbidden::Busy: \"An operation is already running for this service: 49726234-c959-4306-8f78-f8330f854658. Please retry later.\" (X-OVH-Query-Id: EU.ext-2.69d8a52f.368002.c4af02ab9f8fa35d12cfc7150b0b517d)"
│ 
│   with ovh_dbaas_logs_output_opensearch_alias.alias[0],
│   on main.tf line 12, in resource "ovh_dbaas_logs_output_opensearch_alias" "alias":
│   12: resource "ovh_dbaas_logs_output_opensearch_alias" "alias" {
│ 
╵
```

### Expected Behavior

The provider should have retried the attach operation. Or the attach operation should be declared in a separate resource to [closely match the underlying API](https://developer.hashicorp.com/terraform/plugin/best-practices/hashicorp-provider-design-principles#resource-and-attribute-schema-should-closely-match-the-underlying-api). The terraform plan should not fail. All the aliases should be attached to their related stream.

### Actual Behavior

The attach operation has failed because only one operation can be executed at a time. One of the aliases is not attached to its stream. A second terraform apply will replace the alias that is not attached to its stream:

```
  # ovh_dbaas_logs_output_opensearch_alias.alias[0] is tainted, so must be replaced
-/+ resource "ovh_dbaas_logs_output_opensearch_alias" "alias" {
      ~ alias_id     = "1b34bf85-ed8d-422a-9a76-aaed9f4bfd3f" -> (known after apply)
      ~ created_at   = "2026-04-10T09:22:04.086551+02:00" -> (known after apply)
      ~ current_size = 0 -> (known after apply)
      ~ id           = "1b34bf85-ed8d-422a-9a76-aaed9f4bfd3f" -> (known after apply)
      ~ indexes      = [] -> (known after apply)
      ~ is_editable  = true -> (known after apply)
      ~ name         = "ldp-xx-xxxxx-a-stream-0" -> (known after apply)
      ~ nb_index     = 0 -> (known after apply)
      ~ nb_stream    = 0 -> (known after apply)
      ~ streams      = [
          + "47f39741-5466-4d08-b88b-4ae882d73563",
        ]
      ~ updated_at   = "2026-04-10T09:22:18.129198+02:00" -> (known after apply)
        # (3 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

```
terraform apply
```

### References

- #781

### PR DESCRIPTION
**Pull request by jouir**
# Description

Calls to Logs Data Platform can return the following error:

```
OVHcloud API error (status code 403): Client::Forbidden::Busy: "An operation is already running for this service: uuid. Please retry later."
```

When this error is detected:

- Retry the creation and deletion of Graylog streams and OpenSearch aliases
- Retry the attach and detach of Gralog streams to OpenSearch aliases

Fixes #1285.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

```
$ make testacc TESTARGS="-run TestAccResourceDbaasLogsOutputOpensearchAlias_withMultipleStreamsAndMultipleAliases"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccResourceDbaasLogsOutputOpensearchAlias_withMultipleStreamsAndMultipleAliases -timeout 600m -p 10
?       github.com/ovh/terraform-provider-ovh/v2        [no test files]
=== RUN   TestAccResourceDbaasLogsOutputOpensearchAlias_withMultipleStreamsAndMultipleAliases
--- PASS: TestAccResourceDbaasLogsOutputOpensearchAlias_withMultipleStreamsAndMultipleAliases (287.24s)
PASS
ok      github.com/ovh/terraform-provider-ovh/v2/ovh    287.255s
?       github.com/ovh/terraform-provider-ovh/v2/ovh/datasources/cloud_project_rancher  [no test files]
?       github.com/ovh/terraform-provider-ovh/v2/ovh/helpers    [no test files]
testing: warning: no tests to run
PASS
ok      github.com/ovh/terraform-provider-ovh/v2/ovh/helpers/hashcode   (cached) [no tests to run]
?       github.com/ovh/terraform-provider-ovh/v2/ovh/ovhwrap    [no test files]
?       github.com/ovh/terraform-provider-ovh/v2/ovh/resources/cloud_project_rancher    [no test files]
?       github.com/ovh/terraform-provider-ovh/v2/ovh/types      [no test files]
```

**Test Configuration**:
* Terraform version: `terraform version`: Terraform v1.14.7
* Existing HCL configuration you used: 
```hcl
data "ovh_dbaas_logs_cluster" "logs_cluster" {
  service_name = "ldp-xx-xxxxx"
}

resource "ovh_dbaas_logs_output_graylog_stream" "stream" {
  count        = 2
  service_name = data.ovh_dbaas_logs_cluster.logs_cluster.service_name
  title        = "stream-${count.index}"
  description  = "stream-${count.index}"
}

resource "ovh_dbaas_logs_output_opensearch_alias" "alias" {
  #count        = 0
  count        = length(ovh_dbaas_logs_output_graylog_stream.stream)
  service_name = data.ovh_dbaas_logs_cluster.logs_cluster.service_name
  description  = "alias for stream-${count.index}"
  suffix       = "stream-${count.index}"
  streams = [
    ovh_dbaas_logs_output_graylog_stream.stream[count.index].id
  ]
}
```

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or issues
- [x] I have added acceptance tests that prove my fix is effective or that my feature works
- [x] New and existing acceptance tests pass locally with my changes
- [x] I ran successfully `go mod vendor` if I added or modify `go.mod` file

### CODE REVIEW

File: ovh/resource_dbaas_logs_output_graylog_stream.go [hunk 1]
```diff
@@ -235,8 +238,18 @@ func resourceDbaasLogsOutputGraylogStreamCreate(ctx context.Context, d *schema.R
 		"/dbaas/logs/%s/output/graylog/stream",
 		url.PathEscape(serviceName),
 	)
-	if err := config.OVHClient.Post(endpoint, opts, res); err != nil {
-		return diag.Errorf("Error calling post %s:\n\t %q", endpoint, err)
+	err := retry.Retry(d.Timeout(schema.TimeoutCreate)-time.Minute, func() *retry.RetryError {
+		err := config.OVHClient.Post(endpoint, opts, res)
+		if err != nil {
+			if strings.HasPrefix(err.Error(), DBAAS_LOGS_BUSY_ERROR_PREFIX) {
```
Comment (amstuta) [inline ovh/resource_dbaas_logs_output_graylog_stream.go]: I think it would be best to check the error class directly, something like this: 

```
if errOvh, ok := err.(*ovh.APIError); ok && errOvh.Class == "Client::Forbidden::Busy" {
}
```

what do you think ?

Comment (jouir) [reply ovh/resource_dbaas_logs_output_graylog_stream.go]: It's better indeed, thanks for the suggestion. I now use the class.

**Review by amstuta — APPROVED** [review]
