### PR TITLE
fix: Send the correct floatingIp information when creating an instance

### LINKED ISSUE #983: [BUG] 'Unknown parameter' when creating an instance with an existing floating_ip
### Describe the bug
When trying to create an instance with an existing floating_ip attached terraform throws an error:
```
│ Error: calling /cloud/project/[PROJECT_ID]/region/DE1/instance with params &{<nil> <nil> monthly 0xc0007a4e40 0 0xc0007a4c30 <nil> [INSTANCE_NAME] 0xc0007a5060 <nil> <nil> 0xc0007a5b70}:
│ 	"OVHcloud API error (status code 400): Client::BadRequest: \"[network.private.floating_ip] Unknown parameter\" (X-OVH-Query-Id: EU.ext-5.6822f679.2410674.a09c6bb6944492cd7981f4ddce2997df)"
│ 
│   with ovh_cloud_project_instance.node_01,
│   on vpn_ovh.tf line 78, in resource "ovh_cloud_project_instance" "node_01":
│   78: resource "ovh_cloud_project_instance" "node_01" {
```

### Terraform Version

Terraform v1.11.3

### OVH Terraform Provider Version

2.2.0

### Affected Resource(s)

- ovh_cloud_project_instance

### Terraform Configuration Files

```hcl
resource "ovh_cloud_project_instance" "node_01" {
  service_name   = ovh_cloud_project.vpn_dc_ovh.id
  region         = "DE1"
  billing_period = "monthly"
  boot_from {
    image_id = "1241ac38-c075-44bf-a91e-230e72f078b9"
  }
  flavor {
    flavor_id = "6c693dba-c8e8-4ead-a095-46425b43dc0f"
  }
  name = "INSTANCE_NAME"
  ssh_key {
    name = "KEY_NAME"
  }
  network {
    public = false
    private {
      network {
        id        = tolist(ovh_cloud_project_network_private.net.regions_attributes[*].openstackid)[0]
        subnet_id = ovh_cloud_project_network_private_subnet.subnet.id
      }
      gateway {
        id = ovh_cloud_project_gateway.gateway.id
      }
      floating_ip {
        # https://eu.api.ovh.com/console/?section=%2Fcloud&branch=v1#get-/cloud/project/-serviceName-/region/-regionName-/floatingip
        id = "87d52c02-66f2-4d3e-80c1-30b7c4ebf562"
      }
    }
  }
}

```

### Expected Behavior

Instance gehts created with attached floating_ip

### Actual Behavior

Terraform throws error

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### PR DESCRIPTION
**Pull request by amstuta**
# Description

Fixes #983 (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] Test A: `make testacc TESTARGS="-run TestAccCloudProjectInstance_privateNetworkAlreadyExisting"`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or issues
- [x] I have added acceptance tests that prove my fix is effective or that my feature works
- [x] New and existing acceptance tests pass locally with my changes
- [x] I ran succesfully `go mod vendor` if I added or modify `go.mod` file

### CODE REVIEW

File: ovh/resource_cloud_project_instance_test.go [hunk 1]
```diff
@@ -299,3 +299,78 @@ func TestAccCloudProjectInstance_privateNetwork(t *testing.T) {
 		},
 	})
 }
+
+func TestAccCloudProjectInstance_privateNetworkAlreadyExisting(t *testing.T) {
```
Comment (marie-j) [inline ovh/resource_cloud_project_instance_test.go:303]: nitpick 
```suggestion
func TestAccCloudProjectInstance_privateNetworkAlreadyExists(t *testing.T) {
```

**Review by jrm-d — DISMISSED** [review]

**Review by marie-j — DISMISSED** [review]

**Review by mxpetit — APPROVED** [review]
