### PR TITLE
fix: set ip_restrictions type to set on containerregistry_ip_restrict…

### LINKED ISSUE #636: [BUG] list order not consistent in containerregistry_ip_restrictions
### Describe the bug

When applying the same container registry configuration multiple times, the ip_restrictions list is not consistent.
This causes the Managed Registries to be recreated at each apply operation.

### Terraform Version

OpenTofu, but other clients should have the same issue.

### OVH Terraform Provider Version

Latest version

### Affected Resource(s)

- cloud_project_containerregistry_ip_restrictions_registry
- cloud_project_containerregistry_ip_restrictions_management

### Terraform Configuration Files

Any managed registry object with multiple ip_restrictions:

```hcl
  ip_restrictions = [
    { 
      ip_block = "xxx.xxx.xxx.xxx/xx"
      description = "xxxxxxx"
    },
    { 
      ip_block = "xxx.xxx.xxx.xxx/xx"
      description = "xxxxxxx"
    }
]
```
### Expected Behavior

When applying a the same hcl configuration file multiple times, no change should be triggered.

### Actual Behavior

When applying a the same hcl configuration file multiple times, changes were triggered.

### Steps to Reproduce

1. Create a registry with multiple entries in `ip_restrictions`
2. Run `terraform apply` multiple times without any change in the hcl definition.

### Additional context

A workaround is to order the items in the hcl file directly:

```hcl
ip_restrictions= toset([
    {
      "description" : "XXXXXX"
      ip_block = "nnn.nnn.nnn.nnn/nn",
    },
    {
      "description" : "XXXXXX"
      ip_block = "nnn.nnn.nnn.nnn/nn",
    }
])
```

### PR DESCRIPTION
**Pull request by mxm-tr**
…ions

# Description

Changes the type of ip_restrictions in containerregistry_ip_restrictions resources and data from `schema.TypeList` to `schema.TypeSet`.

Fixes #636 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tests have been added to verify that the order of the ip_restrictions does not influence the configuration and the state. 

- [x] Test A: `make testacc TESTARGS="-run ^.*ContainerRegistry.*$"`

**Test Configuration**:
* Terraform version: `terraform version`: Terraform v1.5.6
* Existing HCL configuration you used: 

```hcl

terraform {
  required_providers {
    ovh = {
      source = "ovh/ovh"
      source = "terraform.local/local/ovh"
    }
  }
}

provider "ovh" {
  endpoint           = "ovh-eu"
  application_key    = "xxx"
  application_secret = "yyy"
  consumer_key       = "zzz"
}

data "ovh_cloud_project_capabilities_containerregistry_filter" "regcap" {
  service_name = "xxx"
  plan_name    = "SMALL"
  region       = "GRA"
}

resource "ovh_cloud_project_containerregistry" "registry" {
  service_name = data.ovh_cloud_project_capabilities_containerregistry_filter.regcap.service_name
  plan_id      = data.ovh_cloud_project_capabilities_containerregistry_filter.regcap.id
  region       = data.ovh_cloud_project_capabilities_containerregistry_filter.regcap.region
  name         = "mydockerregistry"
}

resource "ovh_cloud_project_containerregistry_ip_restrictions_management" "my-mgt-iprestrictions" {
  service_name = ovh_cloud_project_containerregistry.registry.service_name
  registry_id  = ovh_cloud_project_containerregistry.registry.id

  ip_restrictions = [
    {
      ip_block    = "192.168.0.1/32"
      description = "xxxxxxx"
    },
    {
      ip_block    = "192.168.0.3/32"
      description = "xxxxxxx"
    }
  ]
}

resource "ovh_cloud_project_containerregistry_ip_restrictions_registry" "my-registry-iprestrictions" {
  service_name = ovh_cloud_project_containerregistry.registry.service_name
  registry_id  = ovh_cloud_project_containerregistry.registry.id

  ip_restrictions = [
    {
      ip_block    = "192.168.0.1/32"
      description = "xxxxxxx"
    },
    {
      ip_block    = "192.168.0.4/32"
      description = "xxxxxxx"
    }
  ]
}


```

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or issues
- [x] I have added acceptance tests that prove my fix is effective or that my feature works
- [x] New and existing acceptance tests pass locally with my changes
- [x] I ran successfully `go mod vendor` if I added or modify `go.mod` file

### CODE REVIEW

File: ovh/types_cloud_project_containerregistry_ip_restrictions.go [hunk 1]
```diff
@@ -22,13 +22,15 @@ func (opts *CloudProjectContainerRegistryIPRestrictionCreateOpts) FromResource(d
...
-
-	for _, ipSet := range iprestrictionsSet {
-		ips = append(ips, CloudProjectContainerRegistryIPRestriction{
-			Description: ipSet.(map[string]interface{})["description"].(string),
-			IPBlock:     ipSet.(map[string]interface{})["ip_block"].(string),
-		})
+	iprestrictionsSet := i.(*schema.Set)
+
+	for _, ipSet := range iprestrictionsSet.List() {
+		if len(ipSet.(map[string]interface{})) > 0 {
```
Comment (amstuta) [inline ovh/types_cloud_project_containerregistry_ip_restrictions.go:28]: from what I see in the resources' schemas this can't happen since we verify that `ip_block` is set, so I guess we can remove this `if`. 
Side node, I'm not sure to understand why the elements in `ip_restrictions` are maps and not nested objects with mandatory fields, this could be updated.

File: ovh/resource_cloud_project_containerregistry_ip_restrictions_management_test.go [hunk 2]
```diff
@@ -58,7 +58,42 @@ resource "ovh_cloud_project_containerregistry_ip_restrictions_management" "my-mg
     {
       ip_block = "121.121.121.121/32"
       description = "my new awesome ip description"
-    }
+    },
+	{
```
[the remark this answers is not in the document]
Comment (mxm-tr) [reply ovh/resource_cloud_project_containerregistry_ip_restrictions_management_test.go:62]: Yes indeed! There seems to be a mix of tabs and spaces in these files

**Comment by amstuta** [comment]
@mxm-tr any news ?

**Comment by mxm-tr** [comment]
> @mxm-tr any news ?

Yes, I had some questions about the comments on the review, cf the comments above

File: ovh/types_cloud_project_containerregistry_ip_restrictions.go (hunk 1 above)
Comment (amstuta) [reply ovh/types_cloud_project_containerregistry_ip_restrictions.go:28]: OK I was not aware of this issue, so keeping the `if` seems like a good idea indeed !
I want to avoid a breaking change so let's keep the resource as-is, and on new resources we won't have this problem as we use `terraform-plugin-framework`.

**Review by amstuta — APPROVED** [review]
