### PR TITLE
fix(okms_secret): detect drift on data change

### LINKED ISSUE #1147: [BUG] No data change recognition in ovh_okms_secret
### Describe the bug
There is a synchronization issue between the secret resource and terraform. In most resources (e.g. storage) some changed values in UI side will be recongnized and correctly shown.

My use case is following:
Create a secret resource with default values in terraform and manually fill in the real secret value as a person. That way there is no secret in the code. In my example is no prevention of changes to the secret data by adding a lifecycle rule.

But in any case I would like to get the real value from my terraform provider. I found a tedious workaround, but that is unintuitive and is a lot of unncessary extra code.

### Terraform Version

Terraform v1.13.4
on darwin_arm64

provider registry.terraform.io/ovh/ovh v2.9.0

### Affected Resource(s)

Please list the resources as a list, for example:
- ovh_okms_secret

### Terraform Configuration Files

```hcl
resource "ovh_okms_secret" "my_credentials" {
  okms_id = var.ovh_secret_manager
  path    = "my_credentials"

  version = {
    data = jsonencode({
      password = "MyPassword"
    })
  }
}

# resource does not contain actual values from secret store
data "ovh_okms_secret" "my_credentials" {
  okms_id      = var.ovh_secret_manager
  path         = ovh_okms_secret.my_credentials.path
  include_data = true
}

output "my_buggy_credentials" {
  value     = ovh_okms_secret.my_credentials.version.data
  sensitive = true
}

output "my_real_credentials" {
  value     = data.ovh_okms_secret.my_credentials.data
  sensitive = true
}
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Go to secret manager and change the password to a new value
3. `terraform apply` again
4. `terraform output my_buggy_credentials`
5. `terraform output my_real_credentials`

### Debug Output

For step 4
```
"{\"password\":\"MyPassword\"}"
```

For step 5
```
"{\"password\":\"MyChangedPassword\"}"
```

### Expected Behavior

1. Terraform should have actually recognized that the resource is not correct and changed the value back to my password.
2. Terraform should not yield different values for the same entity. Resource and data should be equal.

### PR DESCRIPTION
**Pull request by alexGNX**
# Description

The fix is about detecting changes made to an `okms_secret` resource outside of terraform and reconcile the states.

Fixes #1147  (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

```
export TF_ACC=1
export OVH_ENDPOINT=ovh-eu
export OVH_APPLICATION_KEY=...
export OVH_APPLICATION_SECRET=...
export OVH_CONSUMER_KEY=...
export OVH_OKMS=...

# data source tests
go test -timeout 30s -run ^TestAccOkmsSecretDataSource_latestAndVersions$ github.com/ovh/terraform-provider-ovh/v2/ovh
go test -timeout 60s -run ^TestAccOkmsSecretDataSource_latestAndVersions$ github.com/ovh/terraform-provider-ovh/v2/ovh

# resource tests
go test -timeout 90s -run ^TestAccOkmsSecretResource_basicLifecycle$ github.com/ovh/terraform-provider-ovh/v2/ovh
go test -timeout 5m -run TestAccOkmsSecretResource_basicLifecycle github.com/ovh/terraform-provider-ovh/v2/ovh
go test -timeout 5m -run TestAccOkmsSecretResource_casMismatch github.com/ovh/terraform-provider-ovh/v2/ovh
go test -timeout 5m -run TestAccOkmsSecretResource_pathRecreateAndMetadata github.com/ovh/terraform-provider-ovh/v2/ovh
```

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or issues
- [x] I have added acceptance tests that prove my fix is effective or that my feature works
- [x] New and existing acceptance tests pass locally with my changes
- [x] I ran successfully `go mod vendor` if I added or modify `go.mod` file

### CODE REVIEW

File: ovh/resource_okms_secret.go [hunk 1]
```diff
@@ -244,6 +291,34 @@ func buildMetadataPayload(meta *MetadataValue) map[string]any {
...
+		return a == b
+	}
+	normalizedB, err := json.Marshal(objB)
+	if err != nil {
+		return a == b
+	}
+
+	return string(normalizedA) == string(normalizedB)
+}
+
```
Comment (jrm-d) [inline ovh/resource_okms_secret.go]: Maybe we could reduce the amount of []byte <--> string conversions here, for example:
```
func semanticJSONEqual(a, b []byte) bool {
    var objA, objB any

    // Try to parse both as JSON
    if err := json.Unmarshal(a, &objA); err != nil {
        // Not valid JSON, fall back to []byte comparison
        return slices.Equal(a, b)
    }
    if err := json.Unmarshal(b, &objB); err != nil {
        return false
    }

    return reflect.DeepEqual(objA, objB)
} 
```
you would only have to convert input parameters as []byte to call this func

**Review by jrm-d — CHANGES_REQUESTED** [review]

File: ovh/resource_okms_secret.go (hunk 1 above)
Comment (alexGNX) [reply ovh/resource_okms_secret.go]: done, thanks for the suggestion.

**Review by jrm-d — APPROVED** [review]
